server:
  port: 8443

spring:
  application:
    name: auth-server
  config:
    import: optional:configserver:http://config-server:8888/
    cloud:
      config:
        profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka