spring:
  application:
    name: api-gateway
  cloud:
    config:
      profile: dev
  config:
    import: optional:configserver:http://config-server:8888/

server:
  port: 8765

#Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
zuul:
  routes:
    user-release:
      service-id: user-release
      path: /user-release/**
    oauth:
      service-id: auth-server
      path: /auth-server/**
  sensitiveHeaders: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000

management:
  endpoints:
    web:
      exposure:
        include: refresh